// <auto-generated />
using System;
using MAlex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAlex.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAlex.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MAlex.Models.Station", b =>
                {
                    b.Property<int>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationID"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StationID");

                    b.HasIndex("StationName");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationID = 1,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Raml Square",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Raml",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 2,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "El Raml District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Mahattet El Raml",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 3,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Cleopatra District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Cleopatra",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 4,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Sidi Gaber Area",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Sidi Gaber",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 5,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Sporting District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Sporting",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 6,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Ibrahimia Area",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Ibrahimia",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 7,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Azarita District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Azarita",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 8,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Shatby Main Road",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Shatby",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 9,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Smouha Square",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Smouha",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 10,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Kafr Abdou Street",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Kafr Abdou",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 11,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Victoria District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Victoria",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 12,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Mandara Area",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Mandara",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 13,
                            ClosingTime = new TimeSpan(0, 22, 30, 0, 0),
                            Location = "Asafra Main Street",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Asafra",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 14,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Miami Corniche",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Miami",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 15,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Louran District",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Louran",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 16,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Sidi Bishr Area",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Sidi Bishr",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 17,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Asafra Beach Road",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Al Asafra Beach",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 18,
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Location = "Montaza Gardens",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Montaza",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 19,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Stanley Bridge",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Stanley",
                            Status = "Active"
                        },
                        new
                        {
                            StationID = 20,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "Gleem Area",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationName = "Gleem",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("MAlex.Models.Subscrubtion", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("UserID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MAlex.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("TripID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MAlex.Models.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripID"));

                    b.Property<decimal>("Distance")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("EndStationID")
                        .HasColumnType("int");

                    b.Property<int>("StartStationID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripID");

                    b.HasIndex("EndStationID");

                    b.HasIndex("StartStationID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("MetroApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MetroApp.Models.UserTicket", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<int>("TicketID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UserID", "TicketID");

                    b.HasIndex("TicketID");

                    b.HasIndex("UserID");

                    b.ToTable("UserTickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MAlex.Models.Subscrubtion", b =>
                {
                    b.HasOne("MetroApp.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAlex.Models.Ticket", b =>
                {
                    b.HasOne("MAlex.Models.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("MAlex.Models.Trip", b =>
                {
                    b.HasOne("MAlex.Models.Station", "EndStation")
                        .WithMany("EndTrips")
                        .HasForeignKey("EndStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MAlex.Models.Station", "StartStation")
                        .WithMany("StartTrips")
                        .HasForeignKey("StartStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("MetroApp.Models.UserTicket", b =>
                {
                    b.HasOne("MAlex.Models.Ticket", "Ticket")
                        .WithMany("UserTickets")
                        .HasForeignKey("TicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroApp.Models.User", "User")
                        .WithMany("UserTickets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MetroApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MetroApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MetroApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAlex.Models.Station", b =>
                {
                    b.Navigation("EndTrips");

                    b.Navigation("StartTrips");
                });

            modelBuilder.Entity("MAlex.Models.Ticket", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("MAlex.Models.Trip", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MetroApp.Models.User", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
